stages:
  - install
  - build
  # - test
  - deploy

services:
  - docker:dind

build:code:
  stage: install
  tags:
    - fargate
  image: decentraland/ci-node:latest
  variables:
    PULUMI_STACK: "website-talent-hub"
  only:
    - master
    - staging
    - release
  script:

    # install dependencies
    - npm ci --cache .npm --prefer-offline

    # setup dcl environment
    - export PATH="$PATH:$HOME/.pulumi/bin"
    - source dcl-env

    # setup project environment
    - pulumi login -c "s3://$STATE_BUCKET/"
    - >
      if pulumi stack select "$PULUMI_STACK-$ENVIRONMENT"; then
        echo "[stack $stack] Stack exists ✅";
      else
        pulumi stack init "$PULUMI_STACK-$ENVIRONMENT"
        echo "[stack $stack] Stack created ✅";
      fi

    - source ./node_modules/.bin/setup-environment

    - env | grep GATSBY_ > .env
    - echo .env

    # push server
    - dcl-lock-sync
    - dcl-up $PULUMI_STACK
    - dcl-sync-release

    - pulumi stack output --show-secrets
